import type { ProductItem } from './types';

// Top advertisers ranked by popularity/brand recognition
// Used for "Featured" sort on Home and Browse pages
export const TOP_ADVERTISERS: string[] = [
  // Tier 1: Top brands / SaaS / products (weight 6x)
  'Google',
  'Nike',
  'Netflix',
  'Notion',
  'Hubspot',
  'Hims',
  'Kajabi',
  'Roku',
  'BetterHelp',
  'AG1',
  'Intercom',
  'Deel',
  'Riverside',
  'Pacaso',
  'PodPitch',
  'Huel',
  'Writer',
  'Lindy.ai',
  'Authory',
  'Betterment',
  'Long Angle',
  'Gamma',
  'Stack Influence',
  'Rippling',
  "Brad's Deals",
  'Monday.com',
  'Proton',
  'Shutterstock',
  'Fellow',
  // Tier 2: Strong brands (weight 3.5x)
  'The Hustle',
  'Vanta',
  'Bill.com',
  'Stan',
  'Superhuman AI',
  'Mode Mobile',
  'RYSE',
  'Pressmaster DMCC',
  'Attio',
  'HoneyBook',
  'Artisan',
  'AdQuick',
  'Salesforge',
  'Wispr Flow',
  'Neurons',
  'CBDistillery',
  'Fyxer AI',
  'guidde',
  'Masterworks',
  'Udacity',
  'Synthflow',
  'Coactive',
  'Levanta',
  'Axios HQ',
  'Fisher Investments',
  'Mintlify',
  'Neo',
  'Haystack',
  'insightsoftware',
  'you.com',
  'Immersed',
  'BetterSleep',
  'Maven AGI',
  'Vinovest',
  'RAD Intel',
  'CompareCredit',
  'Intrepid Travel',
  'ListKit',
  // Tier 3: Niche / smaller brands (weight 2x)
  'Typeless',
  'Medik8',
  'The Black Tux',
  'Ladders',
  'SelectSoftware Reviews',
  'Delve',
  'Bullseye Trades',
  'Elite Trade Club',
  'Livelong Media',
  'MEDVi',
  'Wallstreet Prep',
  'Gladly.ai',
  'beehiiv',
  'reMarkable',
  'EnergyX',
  'Gethookd',
  'SuppCo',
  'Particle for Men',
  'Pique Life',
  'KeepCart',
  'Allara',
  'Celluma',
  'JRNYS',
  'Cheers',
  'Tabs',
  'CoW',
  'Inflow',
  'Counterflow',
  'BELAY',
  'Go-to-Millions',
  'Acadia Learning',
  'Relatable',
  'Contra',
  'AltIndex',
  'Masterworks (Archive)',
  // Tier 4: Media / newsletter companies + smaller brands (weight 1x)
  'Mood Gummies',
  'Growth School',
  '1440 Media',
  'Morning Brew',
  'The Rundown AI',
  'Mindstream',
  'The Daily Upside',
  'The Deep View',
  'Money.com',
  'The Feed',
  'Marketing Against The Grain',
  'The Pour Over',
  'Finance Buzz',
  'The Marketing Millennials',
  'The AI Report',
  'The Code',
  'Westbound & Down',
  'IT Brew',
  'Fintech Takes',
  'I Hate It Here',
  'Brew Markets',
  'Healthcare Brew',
  'The Flyover',
  'Forward Future AI',
  'Miso Robotics',
  'The Bouqs Co.',
  'Stocks & Income',
  'GURU 2025',
  'Crypto101',
  'AI Capital News',
  'Tangle',
  'Analytica Investor',
  'Confluence VC',
  'Motley Fool Money',
  'Zipchat',
  'AIR',
  'RunDot',
  'Ground News',
  'Consensus',
  'Polymarket',
  'Haus',
  'EverQuote',
  'Skej',
  'Value Investor Daily',
  'Klondike Royalties',
  'Inspire Financial',
  'VaultCraft',
  'Pinata',
  'Bright Data',
  'Lysted',
  'Chargeflow',
  'TaylorMade',
  'Deepgram',
  'Hungryroot',
  'Speedeon Data',
  'Syllaby.io',
  'Decentraland',
  'Wing Assistant',
  'Black Crow AI',
  'AI with Allie',
  'Convergence AI',
  'inFlow Inventory',
  'Indy AI',
  'Contrarian Thinking',
  'Collective',
  'Cizzle Bio',
  'Author.Inc',
  'Momentous',
  'Tovala',
  'Peak Bank',
  'Uniswap',
  'Fay Nutrition',
  'Kojo',
  'StartEngine',
  'ClickUp',
  'Climatize',
  'HomeBuddy',
  'Oceans',
  'Premium Ghostwriting Academy',
  'Enterpret',
  'Med-X',
  'Lumen',
  'DIRTEA',
  'Oneleet',
  'The Oxford Club',
  'Nautilus',
  'trainwell',
  'Lulu',
  'Land.id',
  'Every.io',
  'Wall Street Prep',
  'Limitless',
  'Besolo',
  'Galactic Fed',
  'ACTIVE',
  'QuarterZip',
  'that startup guy',
  'Raptive',
  'CEIFX',
  'Codeium',
  'flowkey',
  'Perpetua Life',
  'Ahrefs',
  'Surf Lakes',
  'Headway',
  'Agora',
  'Remofirst',
  'Spot Pet Insurance',
  'Upmarket',
  '6AM City',
  'DESelect',
  'JKBX',
  'Branded Bills',
  'Babbel',
  'Cornbread Hemp',
  'Korrect',
  'POP',
  'GoldCo',
  'KwaKwa',
  'Ohai.ai',
  'DubApp',
  'Pioneer by Fin',
  'Timeplast',
  'ELEKS',
  'Rewardful',
  'ExpressPros',
  'VantagePoint',
  'No Scrubs',
  'Ubiquitous',
  'Booksi',
  'Quince',
  'Boxabl',
  'Walaaxy',
  'TX Flyover',
  'Goody',
  'ClickFunnels',
  'AMASS',
  'The Rave',
  'OneScreen',
  'LookyLoo',
  '4AM Media',
  'Puck News',
  'Marpipe',
  'BusinessLoans.com',
  'Sidebar',
  'Timeline',
  'INMO',
  'Compare.com',
  'Superpower',
  'Republic',
  'Accio AI',
  'Email Based Course',
  'Venice.AI',
  'Ultimate Health Store',
  'Wistia',
  'DraftBoard',
  'Prezi',
  'EnergySage',
  'Grapevine AI',
  'BRUNT Workwear',
  'OneNine',
  'Creatopy',
  'Freespoke',
  'Audien Hearing',
  'Harlo',
  'Abundant Mines',
  'SoundSelf',
  'doola',
  'Webstreet',
  'Agree.com',
  'Kudos',
  'Autopilot',
  'Cartograph',
  'minisocial',
  'ESGold',
  'InstaHeadshots',
  '1906',
  "Altucher's Investment Network",
  'Tiege Hanley',
  'Trust & Will',
  'AARE',
  'SmartNora',
  'Elf Labs',
  'PlayersTV',
  'Bolt.new',
  'Aires Tech',
  'Healthcare.com',
  'Crossbridge',
  'Speks',
  'Yu Tea',
  'Purple Carrot',
  'Kenny Flowers',
  'Little Bellies',
  'BlueAlpha',
  'Planable',
  'Qualia',
  'Blossom Social',
  'Advisor.com',
  'Agoura Health Products, LLC',
  'Cozy Earth',
  'Beyond Blue Media',
  'Blind Barrels',
  'Orbit',
  'TerraCycle',
  'Chime',
  'AISOAP',
  'Virtuix',
  'brodo',
  'Spotloan',
  'Winona',
  'James Allen',
  'Care2',
  'Imprint',
  'Krete',
  '2U GetSmarter Online Ltd',
  'Choose Your Horizon',
  'Kraken',
  'Queensboro',
  'Alibaba Lens',
  'EarningsHub',
  'FL Flyover',
  'Pirouette',
  'All About Change',
  'Plan to Eat',
  'Beverly Hills MD, LLC',
  'Monday.com',
  // Bedtime Stories with Netflix Jr. merged into Netflix
  'PromoTix',
  'Inbox Hacking',
  'Storage Scholars',
  'Mastermind',
  'Nucific',
  'Vero3',
  'Anvara',
  'Straight+',
  'AptDeco',
  'Insurify Auto',
  'Dex',
  'Empire Today',
  'Death & Co.',
  'Surmount AI',
  'Trading Tips',
  'Fisico',
  'Keith Prowse',
  'Ask CMO',
  'Moonwlkr',
  'Unspun Updates',
  'Alibaba',
  'Public Rec',
  'Critical Start',
  'Stacked Marketer',
  'California Pet Partners, LLC',
];

// Curated products with rich metadata
export const PRODUCTS: ProductItem[] = [];
